//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRServer.Source.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRServer.Source.Resources.ServerResources", typeof(ServerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shutdown.
        /// </summary>
        internal static string Text_Server_Command_Name_Shutdown {
            get {
                return ResourceManager.GetString("Text_Server_Command_Name_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait before shutting down the server.
        /// </summary>
        internal static string Text_Server_Command_Shutdown_Param_Delay {
            get {
                return ResourceManager.GetString("Text_Server_Command_Shutdown_Param_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuts the server down.
        /// </summary>
        internal static string Text_Server_Help_Command_Shutdown {
            get {
                return ResourceManager.GetString("Text_Server_Help_Command_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Text_Server_Lobby_Channel_Name {
            get {
                return ResourceManager.GetString("Text_Server_Lobby_Channel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Text_Server_Match_Channel_Name {
            get {
                return ResourceManager.GetString("Text_Server_Match_Channel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer.
        /// </summary>
        internal static string Text_Server_Observer_Channel_Name {
            get {
                return ResourceManager.GetString("Text_Server_Observer_Channel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has successfully connected to the server!.
        /// </summary>
        internal static string Text_Server_Player_Connected_Notice {
            get {
                return ResourceManager.GetString("Text_Server_Player_Connected_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has gone linkdead. Suspending for possible reconnection!.
        /// </summary>
        internal static string Text_Server_Player_Linkdead_Notice {
            get {
                return ResourceManager.GetString("Text_Server_Player_Linkdead_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed completely from the server after an excessively long link death..
        /// </summary>
        internal static string Text_Server_Player_Linkdead_Timeout_Notice {
            get {
                return ResourceManager.GetString("Text_Server_Player_Linkdead_Timeout_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has successfully reconnected to the server!.
        /// </summary>
        internal static string Text_Server_Player_Reconnected_Notice {
            get {
                return ResourceManager.GetString("Text_Server_Player_Reconnected_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed completely!.
        /// </summary>
        internal static string Text_Server_Player_Removed_Notice {
            get {
                return ResourceManager.GetString("Text_Server_Player_Removed_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Lost Cities Server **.
        /// </summary>
        internal static string Text_Server_Startup_Greeting {
            get {
                return ResourceManager.GetString("Text_Server_Startup_Greeting", resourceCulture);
            }
        }
    }
}
